 # Use an official Python runtime as a parent image
 FROM python:3.8-slim

 # Set the working directory in the container
 WORKDIR /app

 # Copy the current directory contents into the container at /app
 COPY . /app

 # Install any needed packages specified in requirements.txt
 RUN pip install --no-cache-dir -r requirements.txt

 # Install Nginx
 RUN apt-get update && apt-get install -y nginx

 # Copy Nginx configuration file
 COPY nginx.conf /etc/nginx/nginx.conf

 # Make ports 80, 443, 8080, and 9090 available to the world outside this container
 EXPOSE 80
 EXPOSE 443
 EXPOSE 8080
 EXPOSE 9090

 # Define environment variable
 ENV NAME World

 # Start Nginx and your Python app
 CMD nginx -g 'daemon off;' & python app.py